spring:
  jpa:
    # 전송 쿼리 확인
    # query 確認
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후 data.sql 실행
    # テーブル作成後にdata.sqlを実行
    defer-datasource-initialization: true

